name: Qodana

on:
  schedule:
    - cron: "39 6 * * 2"

  workflow_call:
    secrets:
      ## Secrets: Qodana Token
      QODANA_TOKEN:
        required: true
        description: "Qodana reporting token"

      ## Buildless API key
      BUILDLESS_APIKEY:
        required: true
        description: "Buildless API key"

  workflow_dispatch:
    secrets:
      QODANA_TOKEN:
        required: true
        description: "Qodana reporting token"
      BUILDLESS_APIKEY:
        required: true
        description: "Buildless API key"

jobs:
  scan:
    name: Qodana
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit

      - name: "Setup: Checkout"
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v3
      - name: "Setup: JDK 19"
        uses: buildjet/setup-java@89ddc594b1d96eada357fc2824610d5d6650f2da # v4
        with:
          distribution: "adopt-hotspot"
          java-version: "19"
      - name: "Qodana Scan"
        uses: JetBrains/qodana-action@a8f1498ffa04bd69e4770670c0cc9c6ce2ee7ca1 # main
        continue-on-error: true
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
          BUILDLESS_APIKEY: ${{ secrets.BUILDLESS_APIKEY }}
