name: CI

on:
  ## Event: Merge group checks
  merge_group: {}

  ## Event: Push on `main` or `stable`
  push:
    branches:
      - main
      - stable
    tags:
      - "v*"

  ## Event: PR
  pull_request:
    types:
      - opened
      - closed
      - reopened
      - synchronize
    paths:
      ## Trigger: Global changes/release
      - ".version"
      - ".release"

      ## Trigger: Server Changes
      - "gradle.properties"
      - "*.kts"
      - "**/*.kts"
      - "**/*.kt"
      - "**/*.java"
      - "**/*.properties"
      - "app/server/**"
      - "gradle/**"

env:
  CI: true
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  BUILDLESS_APIKEY: ${{ secrets.BUILDLESS_APIKEY }}

jobs:
  ## Build: Gradle Plugin
  build-plugin:
    name: "Build"
    uses: elide-dev/build-infra/.github/workflows/jvm.gradle.yml@main
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      BUILDLESS_APIKEY: ${{ secrets.BUILDLESS_APIKEY }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    permissions:
      checks: write
      pull-requests: read
      id-token: write
      contents: read
    with:
      jvm: '11'
      label: "Gradle Plugin"
      runner: ubuntu-latest
      action: 'build test koverXmlReport check sonar'
      flags: '--scan --stacktrace'
      coverage: true

  ## Checks: CodeQL
  check-codeql:
    name: "Check"
    needs: ["build-plugin"]
    uses: ./.github/workflows/module.codeql.yml
    secrets:
      BUILDLESS_APIKEY: ${{ secrets.BUILDLESS_APIKEY }}
    permissions:
      checks: write
      pull-requests: read
      id-token: write
      contents: read
      actions: read
      security-events: write

  ## Checks: Detekt
  check-detekt:
    name: "Check"
    needs: ["build-plugin"]
    uses: ./.github/workflows/module.detekt.yml
    secrets:
      BUILDLESS_APIKEY: ${{ secrets.BUILDLESS_APIKEY }}
    permissions:
      checks: write
      pull-requests: read
      id-token: write
      contents: read
      actions: read
      security-events: write

  ## Checks: Qodana
  check-qodana:
    name: "Check"
    needs: ["build-plugin"]
    uses: ./.github/workflows/module.qodana.yml
    secrets:
      QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
      BUILDLESS_APIKEY: ${{ secrets.BUILDLESS_APIKEY }}
    permissions:
      checks: write
      pull-requests: read
      id-token: write
      contents: read
      actions: read
      security-events: write

  ## Checks: Dependency Review
  dependency-review:
    name: "Dependency Review"
    needs: ["build-plugin"]
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: "Setup: Checkout"
        uses: actions/checkout@v3
      - name: "Analysis: Dependency Review"
        uses: actions/dependency-review-action@v3
